### ISSUE TITLE
找不到硬盘

### ISSUE THREAD

**Issue by haol666** [Shaw-fung/dell-5175-efi-opencore-oc#3]
设置好机型后启动找不到硬盘。

**Comment by Shaw-fung** [comment]
设置机型后启动找不到硬盘？这不存在吧，我也是设置好机型的，完全可以使用，你设置的什么机型？修改了哪些？方便截图看一下吗？

**Comment by haol666** [comment]
就是5175啊怀疑是不是bios哪里设置有问题我的bios版本是1.7.0，nvme是sandisk ultra。不知道是硬盘问题还是哪的问题。机型设置是MacBook9,1 这部分应该没问题。

**Comment by haol666** [comment]
@Shaw-fung 想起一个可能的原因，你用的ssd是sata协议的还是m2 协议的啊。啥型号？

**Comment by Shaw-fung** [comment]
> @Shaw-fung 想起一个可能的原因，你用的ssd是sata协议的还是m2 协议的啊。啥型号？

INTEL SSDSCKGF256A5 SATA 256GB

**Comment by haol666** [comment]
我用的这个是nvme通道，5175的m2接口两种协议都兼容，应该是少了nvme的驱动

**Comment by Shaw-fung** [comment]
> 我用的这个是nvme通道，5175的m2接口两种协议都兼容，应该是少了nvme的驱动

你没有设置机型之前可以安装并进入macOS吗？

**Comment by haol666** [comment]
不设置机型有个id错误的提示，我就全设置了。目前用老的opencore0.6的版本能识别硬盘。

**Comment by haol666** [comment]
https://github.com/haol666/dell-5175-opencore-nvme ，自己做了一个版本，0.76的需要改cfglock和缓存大小。触摸板可以当鼠标用，不支持手势，睡眠唤醒可能还有问题T_____T
